<?php

return [
    'name' => 'SMA Cendekia Nusantara',
    'short_name' => 'Cendekia Nusantara',
    'tagline' => 'Tempat Bertumbuh, Berprestasi, dan Menginspirasi',
    'description' => 'Sekolah menengah atas yang membangun generasi unggul melalui pendidikan berkualitas, berkarakter, kreatif, dan adaptif terhadap perkembangan teknologi.',
    'address' => 'Jl. Pendidikan Raya No. 45, Bandung, Jawa Barat 40132',
    'phone' => '(022) 8765-4321',
    'email' => 'info@cendekianusantara.sch.id',
    'social_links' => [
        ['label' => 'Facebook', 'url' => '#', 'icon' => 'facebook'],
        ['label' => 'Instagram', 'url' => '#', 'icon' => 'instagram'],
        ['label' => 'YouTube', 'url' => '#', 'icon' => 'youtube'],
        ['label' => 'Twitter', 'url' => '#', 'icon' => 'twitter'],
    ],
    'principal' => [
        'name' => 'Drs. H. Bambang Nugroho, M.Pd.',
        'position' => 'Kepala SMA Cendekia Nusantara',
        'photo' => 'images/principal/kepala-sekolah.jpg',
        'photo_alt' => 'Kepala Sekolah SMA Cendekia Nusantara, Drs. H. Bambang Nugroho, M.Pd.',
        'message' => 'Setiap anak lahir dengan potensi yang berbeda, dan tugas kami adalah menemukan serta menumbuhkannya. Di Cendekia Nusantara, pembelajaran tidak berhenti di ruang kelas — kami mendampingi siswa berpikir kritis, berkarya, dan berakhlak baik. Kami percaya sekolah terbaik adalah sekolah yang membuat siswanya berani bermimpi dan siap mewujudkannya.',
    ],
    'hero' => [
        'headline' => 'Tempat Bertumbuh, Berprestasi, dan Menginspirasi',
        'description' => 'Membangun generasi unggul melalui pendidikan yang berkualitas, berkarakter, kreatif, dan adaptif terhadap perkembangan teknologi.',
        'image' => 'images/hero/campus.jpg',
        'image_alt' => 'Gedung utama SMA Cendekia Nusantara dengan siswa beraktivitas di halaman sekolah',
        'primary_cta' => ['label' => 'Jelajahi Sekolah', 'href' => '/profil'],
        'secondary_cta' => ['label' => 'Daftar PPDB', 'href' => '/ppdb'],
        'floating_stat' => ['value' => '98%', 'label' => 'Lulusan diterima di PTN & PTS favorit'],
    ],
    'statistics' => [
        ['id'=>'students','value'=>1250,'suffix'=>'+','label'=>'Siswa Aktif','icon'=>'students'],
        ['id'=>'teachers','value'=>85,'suffix'=>'+','label'=>'Guru & Staff','icon'=>'teachers'],
        ['id'=>'achievements','value'=>120,'suffix'=>'+','label'=>'Prestasi','icon'=>'achievements'],
        ['id'=>'years','value'=>25,'suffix'=>'+','label'=>'Tahun Berdiri','icon'=>'years'],
    ],
    'navigation' => [
        ['label'=>'Beranda','href'=>'/'],
        ['label'=>'Profil','href'=>'/profil'],
        ['label'=>'Akademik','href'=>'/akademik'],
        ['label'=>'Prestasi','href'=>'/prestasi'],
        ['label'=>'Berita','href'=>'/berita'],
        ['label'=>'Galeri','href'=>'/galeri'],
        ['label'=>'Kontak','href'=>'/kontak'],
    ],
    'footer_navigation' => [
        ['label'=>'Beranda','href'=>'/'],
        ['label'=>'Profil','href'=>'/profil'],
        ['label'=>'Akademik','href'=>'/akademik'],
        ['label'=>'Prestasi','href'=>'/prestasi'],
        ['label'=>'Berita','href'=>'/berita'],
        ['label'=>'Galeri','href'=>'/galeri'],
        ['label'=>'Kontak','href'=>'/kontak'],
        ['label'=>'Agenda','href'=>'/agenda'],
        ['label'=>'PPDB','href'=>'/ppdb'],
    ],
    'news' => [
        ['id'=>1,'title'=>'Tim Olimpiade Sains Raih Medali Emas Tingkat Nasional','slug'=>'tim-olimpiade-sains-raih-medali-emas-nasional','excerpt'=>'Lima siswa kami membawa pulang medali emas dan perak dari Olimpiade Sains Nasional setelah pembinaan intensif selama satu semester.','image'=>'images/news/olimpiade.jpg','image_alt'=>'Siswa memegang trofi dan sertifikat kemenangan olimpiade sains di atas panggung','category'=>'Prestasi','published_at'=>'2026-07-28'],
        ['id'=>2,'title'=>'Kelas Robotika & AI Resmi Masuk Kurikulum Pilihan','slug'=>'kelas-robotika-ai-masuk-kurikulum-pilihan','excerpt'=>'Mulai tahun ajaran ini, siswa dapat memilih peminatan robotika dan kecerdasan artifisial dengan laboratorium komputer yang diperbarui.','image'=>'images/news/robotik.jpg','image_alt'=>'Siswa mengerjakan proyek robotika menggunakan laptop di laboratorium komputer','category'=>'Akademik','published_at'=>'2026-07-14'],
        ['id'=>3,'title'=>'Gerakan Sekolah Hijau: 500 Pohon Ditanam Siswa','slug'=>'gerakan-sekolah-hijau-500-pohon-ditanam-siswa','excerpt'=>'Program Adiwiyata tahun ini melibatkan seluruh angkatan dalam penanaman pohon dan pengelolaan bank sampah sekolah.','image'=>'images/news/adiwiyata.jpg','image_alt'=>'Siswa menanam pohon bersama di halaman sekolah','category'=>'Kegiatan','published_at'=>'2026-06-30'],
    ],
    'events' => [
        ['id'=>1,'title'=>'Open House & Tur Kampus Sekolah','date'=>'2026-08-16','time'=>'08.00 – 12.00 WIB','location'=>'Aula Utama','description'=>'Calon siswa dan orang tua dapat mengenal fasilitas, kurikulum, serta bertemu langsung dengan wali kelas dan guru mata pelajaran.'],
        ['id'=>2,'title'=>'Pentas Seni & Festival Budaya Nusantara','date'=>'2026-08-23','time'=>'15.00 – 20.00 WIB','location'=>'Lapangan Sekolah','description'=>'Pertunjukan tari tradisional, musik, dan bazar karya siswa dari seluruh ekstrakurikuler seni.'],
        ['id'=>3,'title'=>'Workshop Persiapan Kuliah & Beasiswa','date'=>'2026-09-05','time'=>'09.00 – 14.00 WIB','location'=>'Ruang Multimedia','description'=>'Sesi pendampingan pemilihan jurusan, strategi seleksi nasional, dan informasi beasiswa dalam serta luar negeri.'],
        ['id'=>4,'title'=>'Kompetisi Sains & Matematika Antar Kelas','date'=>'2026-09-19','time'=>'07.30 – 15.00 WIB','location'=>'Gedung Laboratorium','description'=>'Ajang seleksi internal untuk membentuk tim olimpiade sekolah tahun ajaran berikutnya.'],
    ],
    'gallery' => [
        ['id'=>1,'title'=>'Perpustakaan & Ruang Literasi','image'=>'images/gallery/perpustakaan.jpg','image_alt'=>'Siswa membaca di perpustakaan sekolah yang terang dan modern','category'=>'Fasilitas','date'=>'2026-07-20'],
        ['id'=>2,'title'=>'Praktikum Kimia Kelas XI','image'=>'images/gallery/laboratorium.jpg','image_alt'=>'Siswa berjas lab melakukan praktikum kimia di laboratorium','category'=>'Akademik','date'=>'2026-07-11'],
        ['id'=>3,'title'=>'Festival Seni & Budaya','image'=>'images/gallery/seni-budaya.jpg','image_alt'=>'Siswa menampilkan tari tradisional di panggung sekolah','category'=>'Seni','date'=>'2026-06-28'],
        ['id'=>4,'title'=>'Turnamen Basket Antar Kelas','image'=>'images/gallery/olahraga.jpg','image_alt'=>'Siswa bermain basket di lapangan sekolah','category'=>'Olahraga','date'=>'2026-06-15'],
        ['id'=>5,'title'=>'Upacara Bendera Hari Senin','image'=>'images/gallery/upacara.jpg','image_alt'=>'Barisan siswa mengikuti upacara bendera di halaman sekolah','category'=>'Kegiatan','date'=>'2026-06-02'],
        ['id'=>6,'title'=>'Pembelajaran Interaktif di Kelas','image'=>'images/gallery/kelas.jpg','image_alt'=>'Siswa mengangkat tangan saat pembelajaran di dalam kelas','category'=>'Akademik','date'=>'2026-05-24'],
    ],
    'achievements' => [
        ['id'=>1,'title'=>'Medali Emas Olimpiade Sains Nasional (Fisika)','level'=>'Nasional','year'=>'2026','student'=>'Rania Azzahra'],
        ['id'=>2,'title'=>'Juara 1 Kompetisi Robotika Line Follower','level'=>'Provinsi','year'=>'2026','student'=>'Tim Cendekia Robotics'],
        ['id'=>3,'title'=>'Juara 2 Lomba Debat Bahasa Inggris','level'=>'Nasional','year'=>'2025','student'=>'Tim Debat Sekolah'],
        ['id'=>4,'title'=>'Juara 1 Festival Tari Tradisional Pelajar','level'=>'Kota','year'=>'2025','student'=>'Sanggar Nusantara'],
        ['id'=>5,'title'=>'Sekolah Adiwiyata Mandiri','level'=>'Nasional','year'=>'2025','student'=>'SMA Cendekia Nusantara'],
        ['id'=>6,'title'=>'Juara 3 Kejuaraan Basket Pelajar','level'=>'Provinsi','year'=>'2024','student'=>'Tim Basket Putra'],
    ],
];
